import {Mongo} from 'meteor/mongo';
export const Questions = new Mongo.Collection('questions');
export const Profiles = new Mongo.Collection('profiles');
export const ArithmeticQuestions = new Mongo.Collection('arithmetic_questions');
export const Answers = new Mongo.Collection('answers');
export const CountingAnswers = new Mongo.Collection('counting_answers');
export const Emails = new Mongo.Collection('emails');
export const Students = new Mongo.Collection('students');
export const Usernames = new Mongo.Collection('usernames');
export const Challenges = new Mongo.Collection('challenges');